//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_N3
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonchitiet
    {
        public string machitiethd { get; set; }
        public string mahoadon { get; set; }
        public string madichvu { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> thanhtien { get; set; }
    }
}
