//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_N3
{
    using System;
    using System.Collections.Generic;
    
    public partial class phong
    {
        public string maphong { get; set; }
        public string tenphong { get; set; }
        public string maloaiphong { get; set; }
        public string kieuphong { get; set; }
        public string tinhtrangphong { get; set; }
        public Nullable<int> giaphong { get; set; }
    }
}
